---

# ------------------------------------------------------------------------
# Set up networking
#

- name: Fill out and upload /etc/network/interfaces (will be replaced later)
  when: wifi_setup|bool
  template:
    dest: /etc/network/interfaces
    src: etc-network-interfaces.j2
    owner: root
    group: root
    mode: 0600  # hide from go since it will contain WiFi password now
    backup: yes

- name: Remount boot (/boot) as read-write
  command: mount -o remount,rw /boot

- name: Ensure user-editable /boot/ax_raspbpliance dir exists
  when: wifi_setup|bool
  file: path=/boot/ax_raspbpliance state=directory mode=0655

- name: Copy user-editable /etc/network/interfaces mirror in /boot (for symlink)
  command: cp /etc/network/interfaces /boot/ax_raspbpliance/network-interfaces

