---

#
# Remount Pi root and boot filesystem as read-write.
#
# Pass optional tags 'root', 'boot' to narrow scope of actions.
#
# Assumes proper setup has already been done.
#

- name: Remount Read/Write

  hosts: newraspis

  gather_facts: no

  sudo: yes

  tasks:

    - name: Remount root (/) as read-write
      tags: root
      command: mount -o remount,rw /

    - name: Remount boot (/boot) as read-write
      tags: boot
      command: mount -o remount,rw /boot

