---

#
# Hook custom init in /etc/ax_raspbpliance to rc.local.
#

- name: Hook our init script into rc.local
  lineinfile:
    dest: /etc/rc.local
    regexp: "^. /etc/ax_raspbpliance/init$"
    line:    ". /etc/ax_raspbpliance/init"
    insertbefore: "^exit 0"
