---

#
# Ensures /etc/ax_raspbpliance dir exists and has
# an "init" script (to be hooked into rc.local) that starts X
# using custom initrc.
#

- name: Ensure /etc/ax_raspbpliance dir exists
  file: path=/etc/ax_raspbpliance state=directory mode=0655

- name: Upload custom /etc/ax_raspbpliance/kiosk.initrc
  template:
    dest: /etc/ax_raspbpliance/kiosk.xinitrc
    src:   etc-ax_raspbpliance-kiosk.xinitrc.j2
    owner: root
    group: root
    mode:  0755

- name: Upload custom /etc/ax_raspbpliance/init
  template:
    dest: /etc/ax_raspbpliance/init
    src:   etc-ax_raspbpliance-init.j2
    owner: root
    group: root
    mode:  0755

- name: Remount boot (/boot) as read-write
  command: mount -o remount,rw /boot

- name: Ensure user-editable /boot/ax_raspbpliance dir exists
  file: path=/boot/ax_raspbpliance state=directory mode=0655

- name: Create user-editable /boot/ax_raspbpliance URL config
  template:
    dest: /boot/ax_raspbpliance/url.txt
    src:   boot-ax_raspbpliance-url.txt.j2
