---

#
# Push /boot/config.txt to new Raspberry Pi.
#
# The /boot/config.txt acts similar to BIOS config for the Pi
# GPU boot process.
# Here we replace it with one with optiosn we like.
#
# References:
#   - http://elinux.org/RPiconfig
#   - http://elinux.org/R-Pi_ConfigurationFile
#   - http://www.raspberrypi.org/documentation/configuration/config-txt.md
#

- name: Fill out and upload /boot/config.txt
  template:
    dest: /boot/config.txt
    src: boot-config.txt.j2
    owner: root
    group: root
    mode: 0655

